### ISSUE TITLE
Issue with ARMv7 image

### ISSUE THREAD

**Issue by pgrunm** [arsfeld/yarr-build#2]
Hello again,

I noticed a strange bug with the ARMv7 Yarr Docker image and I fear, it's because we're not using the appropriate binary. Instead of ARMv7 it is x64. This results in no content displayed (probably because of the architecture mismatch).

I went through the build action and the logs also run the action to [build x64 Linux](https://github.com/arsfeld/yarr-build/runs/7345547728?check_suite_focus=true#step:8:411) according to the [Dockerfile](https://github.com/nkanaev/yarr/blob/master/dockerfile#L5). I also built an [ARMv7 binary](https://github.com/pgrunm/yarr/actions/runs/2689325733) for myself, uploaded this to my Raspberry Pi and suddenly I could see the UI displayed.

I'm now thinking of different options: 

- Either to create an issue in the upstream original Yarr repository and to ask for an ARMv7 release, or
- to create my own builds or 
- to fix the builds inside this repo. 

What do you prefer @arsfeld?

**Comment by arsfeld** [comment]
You might be having this issue: https://github.com/nkanaev/yarr/issues/82

The fix was not part of any release as far as I know, so it explains why building yourself works, you're probably building from master.

**Comment by pgrunm** [comment]
Ah yes, you're right. This is exactly my problem. I only read the comments and thought it would have been released already, but the commit occured in June, while the last release is from May.
